name: envyweb
description: Envy's web app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: 0.12.1
  intl: ^0.16.1
  image_picker_web: any
  firebase: any	  
  firebase_auth: any	  
  firebase_core: any	
  firebase_storage: any
  cloud_firestore: ^0.14.3+1
  cached_network_image: any
  http_parser: ^3.1.4
  flutter_chat_bubble: ^1.0.2
  get_it: ^5.0.3
  

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true